### ISSUE TITLE
AWS-SDK v3 Compatibility

### ISSUE THREAD

**Issue by thomasmichaelwallace** [thomasmichaelwallace/serverless-better-credentials#20]
pardon for my confusion but does this plugin works with AWS JS SDK v3 (either on node 16 or 18 runtime)? I've been trying to migrate to aws js sdk v3 with no luck

@thomasmichaelwallace all my tooling works just fine, it's just that when deployed using any sdk module throws `CredentialsProviderError: Could not load credentials from any providers`

_Originally posted by @deathemperor in https://github.com/thomasmichaelwallace/serverless-better-credentials/issues/9#issuecomment-1409668094_

**Comment by thomasmichaelwallace** [comment]
My first question is going to be for a minimal reproduction, as the severless frame work deployment aws sdk version should have no bearing on the running lambda code.

Can you share the lambda code and severless yml, and step by step what you're doing to get this error.

I'll also see if I can find some time to setup a working example with V3 of the SDK.

**Comment by deathemperor** [comment]
I created a reproduction and it worked! It helped me debug why my original repo doesn't. It turned out I have a environment var `AWS_PROFILE` (This was for v2 to work, I think). Removed this and now my project works fine on V3

thanks for your kind support opening this issue, @thomasmichaelwallace. Appreciate it. Please close this issue.

**Comment by thomasmichaelwallace** [comment]
No worries - glad you got it sorted!
